language: python
sudo: required
services:
  - docker
os:
  - linux

install:
  - docker pull carinerey/caars_env
before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
  - if [[ $BRANCH == "master" ]]; then export DOCKER_caars="caars"; else export DOCKER_caars="caars_dev"; fi
  - docker build --build-arg BRANCH_DEV=$BRANCH -t carinerey/$DOCKER_caars etc/$DOCKER_caars/ && echo """cd /opt/caars && make test""" > test.sh && docker run -v $PWD:$PWD -t carinerey/$DOCKER_caars bash $PWD/test.sh
script:
  - mkdir test_tuto && cd test_tuto
  - wget https://raw.githubusercontent.com/wiki/CarineRey/caars/src/test_tuto.sh
  - wget https://raw.githubusercontent.com/wiki/CarineRey/caars/src/Tutorial_quick.sh
  - wget https://raw.githubusercontent.com/wiki/CarineRey/caars/src/Tutorial_byyourself.sh
  - sudo bash test_tuto.sh

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO_caars=$DOCKER_USER/$DOCKER_caars
  - export REPO_tuto=$DOCKER_USER/$DOCKER_tuto
  - docker push $REPO_caars
  - docker push $REPO_tuto
