language: c
sudo: required
install: wget https://raw.githubusercontent.com/CarineRey/caars/travis/etc/travis.sh
script: bash -ex .travis.sh
env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.1
os:
  - linux
