language: c
sudo: required
services:
  - docker
os:
  - linux
env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_ENV=$CACHE_DIR/caars_env.tar.gz
cache:
  directories:
  - $CACHE_DIR

before_install:
  - mkdir -p $CACHE_DIR
  - if [ -f ${CACHE_FILE_ENV} ]; then gunzip -c ${CACHE_FILE_ENV} | docker load; fi

install:
  - if [ ! -f ${CACHE_FILE_ENV} ]; then docker pull carinerey/caars_env ; docker save carinerey/caars_env | gzip > ${CACHE_FILE_ENV}; fi

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
  - if [[ $BRANCH == "master" ]]; then DOCKER_caars="caars"; DOCKER_tuto="caars_tuto"; else DOCKER_caars="caars_dev"; DOCKER_tuto="caars_tuto_dev"; fi
  - docker build --build-arg BRANCH_DEV=$BRANCH  -t carinerey/$DOCKER_caars etc/$DOCKER_caars/ && echo """cd /opt/caars && make test""" > test.sh && docker run -t -v $PWD:$PWD carinerey/$DOCKER_caars bash $PWD/test.sh
  - git clone https://github.com/CarineRey/caars.wiki.git caars_wiki_git && docker build -t carinerey/$DOCKER_tuto caars_wiki_git/etc/$DOCKER_tuto && docker run -t -e TUTO_DIR=$PWD/caars_wiki_git/scripts/ -v $PWD:$PWD carinerey/$DOCKER_tuto $PWD/caars_wiki_git/scripts/test_tuto.sh
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO_caars=$DOCKER_USER/$DOCKER_caars
  - export REPO_tuto=$DOCKER_USER/$DOCKER_tuto
  - docker push $REPO_caars
  - docker push $REPO_tuto
