language: c
sudo: required
services:
  - docker
os:
  - linux
script:
  - docker build -t caars etc/caars/
  - echo """cd /opt/caars; make test""" > test.sh
  - docker run -t -v $PWD:$PWD carinerey/caars bash $PWD/test.sh
